name: Uploader

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    # Runs a set of commands using the runners shell
    - name: Upload all files and directories to S3 Bucket
      env:
        S3_UPLOAD_BUCKET: ${{ secrets.S3_UPLOAD_BUCKET}}
      run: |
        aws s3 cp ./* s3://$S3_UPLOAD_BUCKET/ --recursive --acl public-read
